Feature/add tools
ihmcrobotics/ihmc-commons pull request #24
Opened 2024-10-22 14:39 UTC by rjgriffin42

2024-10-22 15:04 UTC, ds58 requested changes

2024-10-22 15:04 UTC, ds58 commented on src/test/java/us/ihmc/commons/robotics/robotSide/RobotSideTest.java
> +	@Test
I think there was a tab inserted here (and also below)

2024-10-22 15:04 UTC, ds58 commented on src/test/java/us/ihmc/commons/robotics/robotSide/SideDependentListTest.java
> +	@Test
I think there was a tab inserted here (and also below)

2024-10-23 15:17 UTC, ds58 commented
Looking good to me

2024-10-23 15:18 UTC, ds58 approved these changes

2024-10-23 16:11 UTC, james-p-foster approved these changes

2024-10-23 18:16 UTC, calvertdw commented on build.gradle.kts
> +
```suggestion
```

2024-10-23 18:17 UTC, calvertdw commented
The README needs to get updated to say something about the new robotics part.

2024-10-23 20:16 UTC, rjgriffin42 commented
I plan on doing that when I do the release once this PR is done.

2024-10-23 21:16 UTC, calvertdw commented
Can you please do the README update in this PR? I would like to review that and have that happen along with these changes.

2024-10-23 22:02 UTC, calvertdw commented on README.md
> +- Tools for workign with deadbands.
typos here

2024-10-23 22:38 UTC, calvertdw approved these changes

2024-10-24 13:27 UTC, merged